### PR TITLE
Changed fontawesome icons to SVG

### LINKED ISSUE #124: Replace web fonts with SVGs
We should replace the couple of FontAwesome icons we use for SVGs, because it's better for accessibility and general happiness (and because @ninjanails told us to).

There's only a couple of instances on the main page so it should be straightfoward: 

jsoxford

### PR DESCRIPTION
**Pull request by AverageMarcus**
Fixes #124

Discussion would be nice...

### CODE REVIEW

**Comment by AverageMarcus** [comment]
I'll update this to include the new sidebar icons

**Comment by AverageMarcus** [comment]
Updated :smile:

**Comment by spikeheap** [comment]
@AverageMarcus this has merge conflicts now, happy to merge it once that's fixed.

**Comment by AverageMarcus** [comment]
Thanks for letting me know @spikeheap. I'll try and take a look this evening.

**Comment by AverageMarcus** [comment]
@spikeheap - It's cool to merge now.

**Comment by spikeheap** [comment]
:boom:

**Pull request merged**
