### PR TITLE
Welcome tweaks

### PR DESCRIPTION
**Pull request by benfoxall**
I've tweaked the welcome page slightly - uses the font from the logo, and replaces the `ul` with a `table`

image

### CODE REVIEW

**Comment by spikeheap** [comment]
It would be good to keep our sponsor logos out of the JSOxford logo. This makes it look like we're part of WO... Other than that this looks good

**Comment by AverageMarcus** [comment]
@spikeheap that image changes, the WO logo is just one of many

**Comment by AverageMarcus** [comment]
You can see an example here: http://output.jsbin.com/luduzeguqa

**Comment by spikeheap** [comment]
@AverageMarcus, changing images is cool, particularly to suit the topics of the talks, but my point still stands. Let's not superimpose sponsor logos on our logo.

**Pull request merged**
