### PR TITLE
Gemojify

### PR DESCRIPTION
**Pull request by benfoxall**
This changes titles from:

image

to…

image

…which is **way better** :+1: :100: :ok_hand: :heart_eyes:

### CODE REVIEW

**Comment by danielthepope** [comment]
I think we should at least wait for me to release v0.0.4 - @AverageMarcus has made some cool looking changes that I want to check out

**Comment by AverageMarcus** [comment]
I still want to fix the issue with it incorrectly converting to emoji too.

**Comment by rjmunro** [comment]
I'm very tempted to link to this: http://stackoverflow.com/a/1732454/3408

**Comment by danielthepope** [comment]
TreeWalker sounds like a good option, but right now unicode only works for Macs. Not everyone (i.e. me) has a Mac, and I still want to see emoji in wonderful colourful glory :wink:

**Comment by danielthepope** [comment]
@benfoxall I just put out 0.0.4 if you want to give that a whirl?

**Comment by omgmog** [comment]
This is now [imojify](https://github.com/danielthepope/imojify) :rocket:

**Comment by richdouglasevans** [comment]
Guys and gals, I _need_ this pull request to be merged something fierce. What can I do to make this happen?

**Comment by spikeheap** [comment]
Yo @richdouglasevans! I think this just needs bumping to imojify 0.0.5 and testing, then it's good :+1:

**Comment by richdouglasevans** [comment]
Then I am going to do this!

> But, er... tomorrow night! :pizza:

**Comment by AverageMarcus** [comment]
But tomorrow night is JS Oxford

**Comment by richdouglasevans** [comment]
:scream: :scream_cat: 

_::gibbers::_

OK... Thursday night!

Hot dang, open source is so... demanding. Like, um, basically... you know?

**Comment by danielthepope** [comment]
Aha, I remember this one.
I got a comment on my blog from someone who said they couldn't get it working. I never followed it up. Open source being so demanding like ;)
I mean, I _think_ the library itself should be working fine. Perhaps it's not as well documented as it should be?

**Comment by omgmog** [comment]
Gonna close this as we've got *new website stuff* in the works

**Pull request closed without merging**
