### PR TITLE
Add more logos

### PR DESCRIPTION
**Pull request by AverageMarcus**
Added NodeSchool and Members photos.

image

### CODE REVIEW

**Comment by spikeheap** [comment]
YESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYESYES

**Comment by AverageMarcus** [comment]
@spikeheap have you taken a look at it in action?

**Comment by spikeheap** [comment]
@AverageMarcus there's more? 👱🔥Can't check it out now, but that's my evening sorted

**Comment by AverageMarcus** [comment]
Modified to just show the members: http://output.jsbin.com/sefazucosa :wink:

**Comment by richdouglasevans** [comment]
Wow+zor :+1: Marcus, you are a legend.

**Comment by AverageMarcus** [comment]
Totally enjoying learning about SVGs :wink:

**Comment by omgmog** [comment]
Very cool. Might be worth punching the opacity of the avatars back a bit? The "JS Oxford" text is a bit unreadable while they're being displayed.

**Comment by AverageMarcus** [comment]
You're right @omgmog, updated.

**Comment by danielthepope** [comment]
THAT IS AWESOME

**Comment by benfoxall** [comment]
This is so so so cool.  I'm in two minds over the inline data-uris, it's awesome to have it self contained, but it's also awesome to have them separate for updating.

**Comment by AverageMarcus** [comment]
Yeah not idea. I may look at having the grunt task update it when it generated the sprite but not right now.

**Pull request merged**
