### PR TITLE
Add CoC link to sidebar

### PR DESCRIPTION
**Pull request by AverageMarcus**

### CODE REVIEW

**Comment by omgmog** [comment]
Still not mentioned in the coc 😞

**Comment by AverageMarcus** [comment]
> ... and if you see @omgmog make sure to report him to the organisers immediately.

That sort of mention, yeah?

**Comment by peterjwest** [comment]
@omgmog this is the JSOx COC, different thing :P

**Comment by AverageMarcus** [comment]
@benfoxall / @spikeheap / @peterjwest - Do you want to merge this?

**Pull request merged**
