### PR TITLE
Add the ability to add more rows

### PR DESCRIPTION
**Pull request by AverageMarcus**
After selecting the initial number of rows, press the `ins` key to add another.

### CODE REVIEW

**Comment by benfoxall** [comment]
This is ace.  Though I've no idea where `ins` is on osx - could we add a different key?

**Comment by AverageMarcus** [comment]
Macs don't have an insert key? Damn those sill keyboard. If you can find a decent key I'll swap it. I was going to use the `+` but on my laptop I have two, both with different key codes and I'm fairly sure they are different to other keyboards.

**Comment by AverageMarcus** [comment]
What about the backtick? Could you go to: http://output.jsbin.com/wukoxojoka and press the backtick? It should say 223

**Comment by benfoxall** [comment]
How about a key combo?  [Mousetrap](https://craig.is/killing/mice) seems like a nice solution.  You could link directly to their cdn https://craig.global.ssl.fastly.net/js/mousetrap/mousetrap.min.js?71631

I reckon `shift+down` could work okay (pretty easy to keep the `ins` key too.)

```js
Mousetrap.bind(['shift+down', 'ins'], function(e) {
    list.innerHTML += row;
});
```

**Comment by AverageMarcus** [comment]
That's a tiny lib, might as well just include it. The page doesn't need to be performant.

**Comment by benfoxall** [comment]
:+1:

**Comment by benfoxall** [comment]
oops

**Comment by AverageMarcus** [comment]
Added the ability to remove last row now too :grin:

**Comment by spikeheap** [comment]
:+1:

**Pull request merged**
