### PR TITLE
Upgrade travis to use containers

### PR DESCRIPTION
**Pull request by AverageMarcus**
See: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

/cc @spikeheap

### CODE REVIEW

**Comment by spikeheap** [comment]
This seems fine (I think we only used the legacy framework because of a sudo call which no longer exists...)

**Comment by richdouglasevans** [comment]
Huh. I don't have much experience with Travis -- CI is almost always Jenkins --  so this ticket was kinda opaque to me.

> Yeah, I read all the commits coming in to learn from them. I don't do a whole lot of web-development day to day.

I have since discovered [what a Travis container is](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) so thanks @AverageMarcus for schooling me. Have some :cake: you're worth it.

> A talk on _Writing Your First Node Module_ at a future JS Oxford complete with Travis integration for n00bs like me might be nice.

**Comment by spikeheap** [comment]
Oooh @richdouglasevans that's a great idea. @peterjwest has been writing a few Node modules recently and might be keen...

**Comment by AverageMarcus** [comment]
Looks like one of the grunt tasks can't run in a container: https://travis-ci.org/jsoxford/jsoxford.github.com/builds/75061788#L720

**Pull request merged**
