### PR TITLE
I'm in your CSS improving aesthetics.

### PR DESCRIPTION
**Pull request by omgmog**
Some tweaks to the styles, to improve things such as:
- visual hierarchy
- consistency
- font size

Also fixed some issues caused by the breakpoints around the header image, and the presentation of the members list on mobile.

Desktop:

Mobile:

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Not sure on the github/twitter/chat headers

**Comment by omgmog** [comment]
I think those three sections could be merged really, and then have a "Follow us" or something header

**Comment by AverageMarcus** [comment]
Yeah sounds better. It just look to spaced out right now.

**Comment by AverageMarcus** [comment]
Also, is there a reason the images aren't showing?

**Comment by spikeheap** [comment]
@omgmog haz the 1337 skillz, sick tekkers, etc.

**Comment by spikeheap** [comment]
That previous comment was a :+1:, btw, though I agree the Twitter/GitHub/etc. need to be merged to make it less cluttered with headers. Nice one @omgmog

**Comment by omgmog** [comment]
@AverageMarcus I just think for some reason the Meetup members thing wasn't working for me from `localhost:4000`, but the sidebar changes shouldn't effect anything there.

Is it worth making the HTML change to the sidebar now? It'll only cause a headache when any of the outstanding PRs are merged as they touch on the HTML, and this is just a SCSS change.

**Comment by omgmog** [comment]
Yep it's because `css/sprites.css` isn't available to me locally?

**Comment by AverageMarcus** [comment]
Ah, you didn't run grunt.

**Comment by spikeheap** [comment]
:+1: :shipit: :fireworks:

**Pull request merged**
