### PR TITLE
If there is a meetup today, fetch the speaker list

### PR DESCRIPTION
**Pull request by AverageMarcus**
Try to auto populate the speaker list from the meetup event description. 

Any text in bold will be assumed to be a talk title. It is possible to modify this after its populated.

If no speakers are found it will prompt for how many and allow manual entry.

### CODE REVIEW

**Comment by benfoxall** [comment]
Brilliant!  That was fast work.

I think it might be more useful to drive this from the page hash, something like:

http://jsoxford.com/welcome.html#221687013

…which would bring in the content from the matching event [/JSOxford/events/221687013/](http://www.meetup.com/JSOxford/events/221687013/).

Ideally, if there was no hash - it would just be the blank logo cycling (it was pretty handy to have the other night).

I reckon this would make it easier for developing/testing (we don't have to wait till there is an event on) and also prevents any last minute fixes on the day (things are usually pretty busy when we've got an event on).

**Comment by AverageMarcus** [comment]
I was going to do that. The only problem is, to call a dynamic endpoint you need to provide an API key. With just checking for meetups today I can use a signed URL which doesn't expose my API key.

**Comment by spikeheap** [comment]
Hi all. Using broad tags like boldness feels like it could be quite brittle, but it did get me thinking. Should we consider flipping things around so we create posts with structured metadata about the events on GitHub, and use that to build the meetup post and populate the welcome page? That way we could get back to having a single source of truth, and keep structure for that source. Also, @peterjwest is a YAML expert so could help us out :+1:

**Comment by benfoxall** [comment]
@AverageMarcus Ah, cool. 

@spikeheap!

Lnug do that for [speakers](https://github.com/lnug/speakers/issues) (check out the milestones for bonus cool points).

There's also [GitEvents](https://github.com/GitEvents) which sync that kind of thing with meetup (I'm not sure how far they've got with it yet).

Though, I guess that's a bigger issue than this.  So I'm going to merge this for now.

**Comment by spikeheap** [comment]
:+1: that's more for the reading list :)

**Comment by AverageMarcus** [comment]
@spikeheap Would you suggest using GitHub issues to build events or the JSOxford website that can then process everything else (rather than the other way around like it currently is).

**Comment by spikeheap** [comment]
@AverageMarcus hmmm, that's an interesting question. I'm probably more a fan of using the website and syncing it with Meetup rather than tying in issues as well – the latter feels a bit more awesome but increases our coupling and the complexity of things. It might get tricky with issues too as we often add org-specific bits in there that wouldn't want to be on the post. That said having a single source could be quite nice...

**Comment by benfoxall** [comment]
Could be really awesome, though the whole move to meetup was painful and sucked up a huge time to get it syncing with the site.  Moving could bring that kind of pain again.  I guess we want something as awesome with as little impact/pain as possible (I'm not sure if rewriting our meetup integration hits that)

**Comment by benfoxall** [comment]
ANYWAY.   THIS PR HAS BEEN CLOSED :x: :hand: :wave: :ocean: :sweet_potato: 

`#moveon #nothingtoseehere`

**Comment by AverageMarcus** [comment]
@spikeheap Shouldn't the website be the single source?

@benfoxall I agree. I'm not sure how difficult it is to have posts push into meetup in a nice way.

**Comment by benfoxall** [comment]
:no_entry: :no_entry_sign: :no_good: :closed_lock_with_key: :lock: :-1:

**Pull request merged**
